### ISSUE TITLE
Mobile menu items with children not opening

### ISSUE THREAD

**Issue by Andymendez100** [inland-empire-software-development/main#105]
**Components that require updating:** 
- Nav

**Tech to be used:** 
- NextJS (React) 

**What is the current behavior:** As of right now, mobile menu items with children do not open on touch. This bug is affecting the **about** and **organization** list items. While there, also adding padding to the "+" icon so that its a bit farther from the text, maybe 5-10px away from the left side. 

![image](https://user-images.githubusercontent.com/3924990/68252007-32655a80-ffd9-11e9-9fed-b7d1310cd144.png)

**What is the new behavior:**  Tapping on a nav item on mobile with a child should show the children.

**Submission information [For PR]**:

All Submissions:
- The commit message follows our guidelines
- Testing steps have been added to this issue or the PR for this issue
- Submission has been tested in all supported browsers

New Feature Submissions:
- Code gone through a code review by at least one other person
- Code has been locally linted `yarn lint`

**Comment by abowler2** [comment]
Put up a PR a little bit ago addressing this:
https://github.com/inland-empire-software-development/main/pull/117

**Comment by lloan** [comment]
@abowler2 I applied it to DEV - it fixes the issue with children not showing up for list items that have them. Awesome! Now there is another issue that could be fixed within this same opened issue. Could you perhaps make it so that when you click on a nav item on mobile the menu disappears? Kind of an odd experience for the page to navigate to where the user wants to go and have the navigation still open. The drawer should close once the user clicks on an item on mobile.

**Comment by abowler2** [comment]
Sure, I'll work on that.  

I saw that Tony put in a new issue for it, so I'll comment over there as well.

**Comment by lloan** [comment]
Sounds good! I'll go ahead and merge your fix for the nav on to master and close the issue here. Thanks for working on this!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lloan** [comment]
@abowler2 this has been merged to master - thanks!
