### ISSUE TITLE
Leadership component: photos & titles for past speaker  

### ISSUE THREAD

**Issue by amacbain1** [inland-empire-software-development/main#54]
Some profile pictures for past speakers are needed, as well as preferred titles. A placeholder iesd logo currently appears if no photo is provided. Also, I have included the name of the talk in place of a title.
![2019-07-15](https://user-images.githubusercontent.com/37091030/61253598-6230df80-a716-11e9-9db5-bf74d44691dc.png)

**Comment by SJT1988** [comment]
Oh, here we go:
[SpencerTrumbore.zip](https://github.com/inland-empire-software-development/main/files/3414108/SpencerTrumbore.zip)

**Comment by lloan** [comment]
@amacbain1 How's it going with procuring the images? Need any help? Thanks!

**Comment by SJT1988** [comment]
I just sent some new pictures to Amber on Github today because she was
requesting them (see "Issues"). I was keeping a lookout for that email from
you with the pics you had but I never got them, I figured you were just
working on some thing else. I can find/make new images based on the style
guide if that's OK with you?

--Spencer

**Comment by SJT1988** [comment]
*Issues #54

**Comment by SJT1988** [comment]
I must be losing my mind because I thought I was sending an email @.@

**Comment by amacbain1** [comment]
Thanks @SJT1988! I'll get you on there soon, I promise :)

**Comment by SJT1988** [comment]
If it will work better to have an image without the background, I have it:
![SpencerTrumbore512](https://user-images.githubusercontent.com/41922761/62003193-2e679980-b0c8-11e9-9d86-0ffb1609379d.png)
![SpencerTrumbore256](https://user-images.githubusercontent.com/41922761/62003194-36273e00-b0c8-11e9-883b-d9f0521b87f5.png)

**Comment by SJT1988** [comment]
Looks like it might be more consistent for you to have a picture of me with a solid background. I don't know how you made the other photos so here is the cutout version of me. You can load it in Photoshop and put whatever kind of background or overlay you need in it. WARNING: it looks terrible on its own with the transparency because Chrome does not seem to support variance in alpha channels--either it's transparent or it's opaque. So these will need new backgrounds. As always, I can make it however you need if you don't have the software.
[SpencerTrumboreTransparentBG.zip](https://github.com/inland-empire-software-development/main/files/3438901/SpencerTrumboreTransparentBG.zip)

**Comment by amacbain1** [comment]
Thanks @SJT1988, I will update. @lloan, yes, please, I still need photos, plus Vast (I'll hit him up on Slack) and the previous week's speaker. Apparently people ignore random strangers asking for personal photos, lol. All other issues with this component will (optimistically) be completed today.

**Comment by lloan** [comment]
@amacbain1 I reached out on Slack to speakers missing images. Will update this once we get these missing images.

**Comment by lloan** [comment]
Looks like we were able to collect a lot more pictures. Will close this one down for now as it was mostly created when we had a lot of placeholders, we're in a good place now.
